CREATE DATABASE BDESCOLA;
USE  BDESCOLA;

select * from aluno;
SELECT*FROM DISCIPLINA; 
select * from CAMPUS;
select * from CURSO;
select * from CURSODISCIPLINA;
select * from DISCIPLINA;
select * from NOTAS;
select * from PROFESSOR;


select A.NOME_ALUNO, (select COUNT(D.NOME_DISCIPLINA) from DISCIPLINA D, NOTAS N where N.ID_ALUNO = A.ID_ALUNO and N.ID_DISCIPLINA = D.ID_DISCIPLINA) as QUANTIDADE_DISCIPLINA from ALUNO A group by A.ID_ALUNO;

select A.nome_Aluno from Aluno A where A.id_Aluno not in(select N.id_Aluno from Notas N); 

select T.NOME_ALUNO, T.QUANTIDADE_DISCIPLINA FROM (select A.nome_Aluno, (select COUNT(D.NOME_DISCIPLINA) from DISCIPLINA D, NOTAS N where
 N.ID_ALUNO = A.ID_ALUNO and N.ID_DISCIPLINA = D.ID_DISCIPLINA) as QUANTIDADE_DISCIPLINA from ALUNO A group by A.ID_ALUNO) T WHERE T.QUANTIDADE_DISCIPLINA < 2;

DELIMITER $$ 

CREATE PROCEDURE LISTAR_ALUNOS (IN quantidade INT)
BEGIN


	SELECT * FROM ALUNO LIMIT quantidade;
    
END $$

DELIMITER ; 
CALL LISTAR_ALUNOS(5);

DELIMITER $$
CREATE PROCEDURE ANALISE_NOTAS( OUT NOME VARCHAR (120), OUT MAX_NOTA DOUBLE, IN IDALUNO INT)
BEGIN

SELECT NOME_ALUNO INTO NOME FROM ALUNO WHERE ID_ALUNO = IDALUNO;

SELECT MAX(N.NOTA) INTO MAX_NOTA FROM NOTAS N WHERE N.ID_ALUNO = IDALUNO;

END$$ 

DELIMITER ; 

SET @NOME = "";
SET @MAX_NOTA = 0;

CALL ANALISE_NOTAS (@NOME, @MAX_NOTA, 8);

SELECT @NOME, @MAX_NOTA;

DELIMITER $$

CREATE PROCEDURE SOMA (INOUT A INT, IN B INT)
	BEGIN 
		
		SET A = B + A;

END$$ 

DELIMITER ;

SET @A = 20;
SET @B = 8;

CALL SOMA(@A,@B);

SELECT @A;

